experiment_name: 'eval_pbasictransformer_gibson4'
project_name: 'indolayout'
model_type: 'indolayout'
data_dir: '/scratch/shantanu/gibson4/new'
split_dir: 'splits/gibson4'
log_dir: '/scratch/shantanu/indolayout/logs'
load_ckpt_path: '/scratch/shantanu/indolayout/weights/train_pbasictransformer_gibson4/20220818-034032/train_pbasictransformer_gibson4-epoch=98-val_loss=0.11.ckpt'
learning_rate: 1e-4
batch_size: 16
num_workers: 8