experiment_name: 'train_amodalbev_gibson4'
model_type: 'amodalbev'
data_dir: '/scratch/shantanu/gibson4/new'
split_dir: 'splits/gibson4'
log_dir: '/scratch/shantanu/perspective_occupancy_map/logs'
weight_dir: '/scratch/shantanu/perspective_occupancy_map/weights'
learning_rate: 1e-4
batch_size: 32
num_workers: 8